#ifndef DEVICE_STATUS_H
#define DEVICE_STATUS_H

typedef enum
{
  DEVICE_STATUS_OK = 0,
  DEVICE_STATUS_INVALID_ARGUMENT,
  DEVICE_STATUS_NOT_INITIALIZED,
  DEVICE_STATUS_NOT_IMPLEMENTED,
  DEVICE_STATUS_NOT_FOUND,
  DEVICE_STATUS_IO_ERROR,
  DEVICE_STATUS_DATA_ERROR,
  DEVICE_STATUS_TIMEOUT,
  DEVICE_STATUS_ID_MISMATCH,
  DEVICE_STATUS_CALIBRATION_ERROR
} DeviceStatus;

#endif /* DEVICE_STATUS_H */
